### ISSUE TITLE
[Brokernode] Troubleshoot attachment redundancy

### ISSUE THREAD

**Issue by rfornea** [opacity/brokernode#29]

**Comment by pzhao5** [comment]
Can you put down a bit more info about this bug?

**Comment by rfornea** [comment]
Yes.  

So basically, if you go to the #development channel in Slack, you'll see a discussion of the issue.  Jet made a tool to visualize what is going on.  

What we are essentially seeing is that for some large files, instead of there being 1 (ideal) or 2 (still good) transactions per chunk address, there are sometimes a larger number of transactions.  What that means is that for example for a 200 MB file, it might be taking up (hypothetically) 1 GB of space on our private tangle.  At this time, we are still troubleshooting what exactly is causing this behavior, so we don't really know yet what we need to fix.

**Comment by rfornea** [comment]
There does seem to be some error coming from the iota API `FindTransactions` method.  The `process_unassigned_chunks` job calls a method in `iota_wrappers`, `verifyChunkMessagesMatchRecord`, which in turn calls `api.FindTransactions`.  We could look into whether this error is coming from IRI or whether it has something to do with our code.

**Comment by nullpilot** [comment]
I've observed one upload over the span of a few hours today, as it gets attached.

First screenshot is pretty much as expected, but still up to 10TX/chunk.  
In the second screenshot only a handful of chunks are missing, but there's already a visible band of overhead. (cyan band)  
Third screenshot it's fully attached, also a lot of overhead (blue/cyan region).
Fourth screenshot is a few hours after all chunks got attached, yet there have been more TX coming.

![diag1](https://user-images.githubusercontent.com/17671117/50798486-d5294b80-12d8-11e9-8c36-63421ea63059.png)
![diag2](https://user-images.githubusercontent.com/17671117/50798487-d5c1e200-12d8-11e9-969c-0d9ff3533534.png)
![diag3](https://user-images.githubusercontent.com/17671117/50798488-d5c1e200-12d8-11e9-8cab-207efdcaffbb.png)
![diag4](https://user-images.githubusercontent.com/17671117/50798489-d5c1e200-12d8-11e9-8a37-0be1d94a080f.png)

**Comment by pzhao5** [comment]
Can you explain the color of the screenshot? Also how to access this tool?
