### ISSUE TITLE
Figure out Remote log solution

### ISSUE THREAD

**Issue by pzhao5** [opacity/brokernode#34]
currently, there is not way to get access the brokernode log. We need some kind of remote log solution to store our log for any debug purpose.

Not sure any good solution out there. Need to spend time to investigate

Aha! Link: https://opacity.aha.io/features/OPQV1-13

**Comment by MrRedPandabear** [comment]
@pzhao5 From t.me/jvott:

J v Ott:
Maybe logstash is an option?

**Comment by MrRedPandabear** [comment]
@MrRedPandabear @jvott hope that was alright

**Comment by MrRedPandabear** [comment]
@MrRedPandabear J v Ott:
Tim maybe you can add the following you can use logstash in combination with: filebeat. 
Filebeat is a lightweight shipper for forwarding and centralizing log data. Installed as an agent on your servers,

**Comment by funkydrummer** [comment]
Looking into Segment and maybe Splunk

**Comment by pzhao5** [comment]
I don't need logstash or filebeat. I only want a central way to view all the logs. For example, if I have 2 server, it would be nice to have web UI to view all of their logs in one place. I am not sure which product it would work the best
